/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author ALYEN
 */
public class VtnPasarTCaAg extends javax.swing.JFrame
{
Nodo r = ManipulaArchivos.carga("Agencia.txt");
public static Nodo o=new Nodo(null, null);

    /**
     * Creates new form VtnBP
     */
    public VtnPasarTCaAg()
    {
        
        initComponents();
        
        Listarcombo();
        Servicio.removeAllItems();
        ListaC2();
        Listarcombo1();
        Servicio1.removeAllItems();
        ListaC21();       
        AutoCompleteDecorator.decorate(Agencia);
    }
private void Listarcombo(){
    
  
    Nodo r1=ManipulaArchivos.carga("Agencia.txt");
Nodo aux=r1;
        while (aux!=null) {
            Agencia.addItem(aux.getEtq());
            aux=aux.getSig();
        }
        
}

private void ListaC2(){
    
    Object n = Agencia.getSelectedItem();
        Nodo aux1=Multilistas.busca(r,(String)n);
        
        
        
        if (aux1==null||aux1.getAbj()==null) {
        Servicio.removeAllItems();
    }else{
    aux1=aux1.getAbj();
        while (aux1!=null) {
            
            Servicio.addItem(aux1.getEtq());
            aux1=aux1.getSig();
        }
        }
}
private void Listarcombo1(){
    
  
    Nodo r1=ManipulaArchivos.carga("Agencia.txt");
Nodo aux=r1;
        while (aux!=null) {
            Agencia1.addItem(aux.getEtq());
            aux=aux.getSig();
        }
        
}
private void ListaC21(){
    
    Object n = Agencia1.getSelectedItem();
        Nodo aux1=Multilistas.busca(r,(String)n);
        
        
        
        if (aux1==null||aux1.getAbj()==null) {
        Servicio1.removeAllItems();
    }else{
    aux1=aux1.getAbj();
        while (aux1!=null) {
            
            Servicio1.addItem(aux1.getEtq());
            aux1=aux1.getSig();
        }
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Agencia = new javax.swing.JComboBox();
        Servicio = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        Agencia1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        Servicio1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Baja de Pacientes");
        setBackground(new java.awt.Color(51, 0, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Agencia: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 35, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edd/imagenes/c1.png"))); // NOI18N
        jButton2.setText("Aceptar");
        jButton2.setContentAreaFilled(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/edd/imagenes/c1.png"))); // NOI18N
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/edd/imagenes/g1.png"))); // NOI18N
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 225, 148, 126));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edd/imagenes/c2.png"))); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/edd/imagenes/c2.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/edd/imagenes/g2.png"))); // NOI18N
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 199, 144, 156));

        Agencia.setEditable(true);
        Agencia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                AgenciaItemStateChanged(evt);
            }
        });
        Agencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgenciaActionPerformed(evt);
            }
        });
        getContentPane().add(Agencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 32, 200, -1));

        Servicio.setEditable(true);
        Servicio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ServicioItemStateChanged(evt);
            }
        });
        Servicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServicioActionPerformed(evt);
            }
        });
        getContentPane().add(Servicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 161, 200, -1));

        jLabel2.setText("Servicio :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 164, -1, -1));

        Agencia1.setEditable(true);
        Agencia1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Agencia1ItemStateChanged(evt);
            }
        });
        Agencia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agencia1ActionPerformed(evt);
            }
        });
        getContentPane().add(Agencia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 32, 200, -1));

        jLabel3.setText("Agencia: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 35, -1, -1));

        Servicio1.setEditable(true);
        Servicio1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Servicio1ItemStateChanged(evt);
            }
        });
        Servicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Servicio1ActionPerformed(evt);
            }
        });
        getContentPane().add(Servicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 161, 200, -1));

        jLabel4.setText("Servicio :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 164, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        
       
        Object A= Agencia.getSelectedItem();
       Object S=Servicio.getSelectedItem();
       Object Ag1=Agencia1.getSelectedItem();
       Object Se1=Servicio1.getSelectedItem();
       
        
        
        if(A==null||S==null){
     JOptionPane.showMessageDialog(this, "No hay Servicios que mostrar");
}
else{
            
            String[]etq= new String[3];
            String[]eta= new String[3];
            Nodo Ag=r;
            Nodo A1=Multilistas.busca(r, (String)A);
            Nodo C=Multilistas.busca(A1.getAbj(), (String)S);
            Nodo auxc=C;
            etq= new String[2];
            etq[0]=(String)A;
            etq[1]=(String)S;
            eta=etq;
            if (A.equals(Ag1)) {
                JOptionPane.showMessageDialog(this, "Es el mismo lugar , elije otro");
            }else{
            r =Multilistas.elimina(r, C, 0, etq);           
             C=C.getAbj();     
             
             Nodo Ser = null;
              etq= new String[2];
              
            etq=insert(r, Ag, Ser, C, etq, (String)S);
            if ((String)Ag1==(String)A && (String)Se1==(String)S) {
                String[] opciones={
                    "No eliminar","eliminar"
                };
                
             int info=JOptionPane.showOptionDialog(null, "No hay otra Agencia que tenga etse servicio, ¿desea eliminar?", "¡Atencion!", 0,0, null, opciones, null);
                
             if (info==1) {
                 etq[0]=(String)Ag1;
                   etq[1]=(String)Se1;
                   o= new Nodo(null, C.getEtq());
                  r=Multilistas.insertar(r, o, 0, etq);
                    JOptionPane.showMessageDialog(this, "No se elimino");
                    dispose();
                    new vtnP().setVisible(true);
                }
            }else{
            System.out.println(etq[0]);
            System.out.println(etq[1]);
             String[]etq2= new String[3];
             etq2[0]=etq[0];
             etq2[1]=etq[1];
             Nodo aux=C;
             
            while(C!=null){
                etq2[2]=C.getEtq();
                System.out.println(C.getEtq());
                Carro ob=new Carro(((Carro)C.getObj()).getAuto(), ((Carro)C.getObj()).getFecha(), ((Carro)C.getObj()).getTer());
                o= new Nodo(ob, C.getEtq());
                r=Multilistas.insertar(r, o, 0, etq2);
                C=C.getSig();
            }
            
             JOptionPane.showMessageDialog(this, "Dato Ingresado Correctamente");
        
        ManipulaArchivos.guarda(r, "Agencia.txt");
 }   
            ManipulaArchivos.guarda(r, "Agencia.txt");
 }   
            dispose();
        new vtnP().setVisible(true);
 }   
        
       
    }//GEN-LAST:event_jButton2ActionPerformed
private String[] insert(Nodo r,Nodo Ag,Nodo Ser,Nodo C,String etq[],String S){
    Nodo aux=C;
    while (aux!=null) {        
        System.out.println(aux.getEtq());
        aux=aux.getSig();
    }
    while (Ag!=null) {
                
                Ser=Ag.getAbj();
                 while (Ser!=null) {
                    
                    System.out.println("Servicio: "+Ser.getEtq());
                    if (Ser.getEtq().equals((String)S)) {
                                etq[0]=Ag.getEtq();
                                etq[1]=Ser.getEtq();
                    
                    
                }        
                    Ser=Ser.getSig();
                               
                }               
               Ag=Ag.getSig();
            }
    return etq;
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
dispose();
        new vtnP().setVisible(true);

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ServicioActionPerformed

    private void ServicioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ServicioItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ServicioItemStateChanged

    private void AgenciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_AgenciaItemStateChanged

        if (evt.getStateChange()==ItemEvent.SELECTED) {
            
            if (this.Agencia.getSelectedIndex()>=0) {
                Servicio.removeAllItems();
                ListaC2();
                
            }
        }
    }//GEN-LAST:event_AgenciaItemStateChanged

    private void AgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgenciaActionPerformed

    private void Agencia1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Agencia1ItemStateChanged
        //
        
        if (evt.getStateChange()==ItemEvent.SELECTED) {
            
            if (this.Agencia1.getSelectedIndex()>=0) {
                Servicio1.removeAllItems();
                ListaC21();
                
            }
        }
        
        
        
    }//GEN-LAST:event_Agencia1ItemStateChanged

    private void Agencia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agencia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Agencia1ActionPerformed

    private void Servicio1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Servicio1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_Servicio1ItemStateChanged

    private void Servicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Servicio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Servicio1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnPasarTCaAg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnPasarTCaAg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnPasarTCaAg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnPasarTCaAg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnPasarTCaAg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Agencia;
    private javax.swing.JComboBox Agencia1;
    private javax.swing.JComboBox Servicio;
    private javax.swing.JComboBox Servicio1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
